version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          name: Deploying to Server 30
          command: |
            ssh $SSH_USER@$SSH_HOST -p 9829 "/var/www/html/circleci-test/deploy.sh"
workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: develop

