version: 2.1
jobs:
  run_project:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            npm install
workflows:
  build_test:
    jobs:
      - run_project

